name: Automated API testing with Bruno
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-bruno-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
        
      - name: Run API Tests
        run: bru run --env books --reporter-html ./results.html
        working-directory: bruno-api-collection

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bruno-test-report
          path: bruno-api-collection/results.html
          retention-days: 1